### ISSUE TITLE
Since hugo 6.0 is that HTML is not rendered anymore by default

### ISSUE THREAD

**Issue by matt6697** [davetcc/hugojoomla#17]
I have now everything as html and a lot of &nbsc; in it. Is that correct that your tool keeps the HTML tags and not convert them? The issue since hugo 6.0 is that HTML is not rendered anymore by default: https://gohugo.io/getting-started/configuration-markup#goldmark

_Originally posted by @joshuabeny1999 in https://github.com/davetcc/hugojoomla/issues/14#issuecomment-907619092_

**Comment by matt6697** [comment]
Work in progress on https://github.com/joomlaext/hugojoomla/tree/feature/htmlbody_to_markdown to convert HTML intro and body to markdown with https://github.com/furstenheim/copy-down

**Comment by matt6697** [comment]
PR #18 merged.

**Comment by joshuabeny1999** [comment]
Hi @matt6697 

I updated the master, did again an Maven Install and that was the console output:
```
log4j: reset attribute= "false".
log4j: Threshold ="null".
log4j: Level value for root is  [INFO].
log4j: root level set to INFO
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n].
log4j: Adding appender named [console] to category [root].
2021-09-02 09:00:43 INFO  ClassPathXmlApplicationContext:581 - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@5cb9f472: startup date [Thu Sep 02 09:00:43 CEST 2021]; root of context hierarchy
2021-09-02 09:00:43 INFO  XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [hugoJoomla.xml]
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
2021-09-02 09:00:43 INFO  DriverManagerDataSource:133 - Loaded JDBC driver: com.mysql.jdbc.Driver
2021-09-02 09:00:44 INFO  JoomlaHugoConverter:86 - Loaded 10 tags into system
2021-09-02 09:00:44 INFO  JoomlaHugoConverter:92 - Starting conversion of Joomla database
2021-09-02 09:00:44 WARN  JoomlaContent:51 - Images for 63 not processed. Error from JSON Parser was null
2021-09-02 09:00:44 WARN  JoomlaContent:51 - Images for 73 not processed. Error from JSON Parser was null
2021-09-02 09:00:44 WARN  JoomlaContent:51 - Images for 74 not processed. Error from JSON Parser was null
2021-09-02 09:00:44 WARN  JoomlaContent:51 - Images for 81 not processed. Error from JSON Parser was null
2021-09-02 09:00:44 WARN  JoomlaContent:51 - Images for 82 not processed. Error from JSON Parser was null
2021-09-02 09:00:44 WARN  JoomlaContent:51 - Images for 85 not processed. Error from JSON Parser was null
2021-09-02 09:00:44 WARN  JoomlaContent:51 - Images for 87 not processed. Error from JSON Parser was null
2021-09-02 09:00:44 WARN  JoomlaContent:51 - Images for 89 not processed. Error from JSON Parser was null
2021-09-02 09:00:44 WARN  JoomlaContent:51 - Images for 90 not processed. Error from JSON Parser was null
2021-09-02 09:00:44 INFO  XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
2021-09-02 09:00:44 INFO  SQLErrorCodesFactory:126 - SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
2021-09-02 09:00:44 ERROR JoomlaHugoConverter:137 - Did not complete conversion
org.springframework.dao.TransientDataAccessResourceException: StatementCallback; SQL [select C.id as id, U.username as username, C.created as created, C.modified as modified, C.introtext as intro,        C.`fulltext` as full, D.path as path, C.title as title, C.alias as alias,
       C.metadesc as metadesc, C.images as images, C.state as state, D.alias as catAlias
from zu1fc_content C, zu1fc_users U, zu1fc_categories D
where C.created_by = U.id
  and D.id = C.catid
  and D.path <> 'uncategorised'
]; Zero date value prohibited; nested exception is java.sql.SQLException: Zero date value prohibited
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:108)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:419)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:474)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:484)
        at com.thecoderscorner.web.hugojoomla.JoomlaHugoConverter.performConversion(JoomlaHugoConverter.java:103)
        at com.thecoderscorner.web.hugojoomla.HugoJoomla.main(HugoJoomla.java:38)
Caused by: java.sql.SQLException: Zero date value prohibited
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:99)
        at com.mysql.cj.jdbc.result.ResultSetImpl.getDate(ResultSetImpl.java:776)
        at com.mysql.cj.jdbc.result.ResultSetImpl.getDate(ResultSetImpl.java:790)
        at com.thecoderscorner.web.hugojoomla.JoomlaHugoConverter.lambda$performConversion$2(JoomlaHugoConverter.java:108)
        at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:93)
        at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:60)
        at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:463)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:408)
        ... 4 more
Caused by: com.mysql.cj.exceptions.DataReadException: Zero date value prohibited
        at com.mysql.cj.result.SqlDateValueFactory.localCreateFromDate(SqlDateValueFactory.java:78)
        at com.mysql.cj.result.SqlDateValueFactory.localCreateFromDate(SqlDateValueFactory.java:51)
        at com.mysql.cj.result.AbstractDateTimeValueFactory.createFromDate(AbstractDateTimeValueFactory.java:69)
        at com.mysql.cj.result.SqlDateValueFactory.localCreateFromDatetime(SqlDateValueFactory.java:120)
        at com.mysql.cj.result.SqlDateValueFactory.localCreateFromDatetime(SqlDateValueFactory.java:51)
        at com.mysql.cj.result.AbstractDateTimeValueFactory.createFromDatetime(AbstractDateTimeValueFactory.java:104)
        at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeDatetime(MysqlTextValueDecoder.java:90)
        at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:86)
        at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:243)
        at com.mysql.cj.protocol.a.result.TextBufferRow.getValue(TextBufferRow.java:132)
        ... 11 more
2021-09-02 09:00:44 INFO  ClassPathXmlApplicationContext:982 - Closing org.springframework.context.support.ClassPathXmlApplicationContext@5cb9f472: startup date [Thu Sep 02 09:00:43 CEST 2021]; root of context hierarchy
``` 

There is a SQL Error. And the chosen folder is empty. Something with the date. I have installed locally latest Joomla 3.10.1. I can only test this one, due i do not have any joomla 4. And maybe i just using this tool to habe a backup of the markdown and maybe later i do a hugo project, when i have more time and find a great theme.

**Comment by davetcc** [comment]
I would suspect modified or created must be blank for one or more rows.

**Comment by davetcc** [comment]
Can you run a query on the db where modified is null or created is null for table zu1fc_content  or even where they have none date values. In this case it appear to be 0.

**Comment by davetcc** [comment]
@matt6697 I’m on my phone at the moment. But when I get back I can give you write access to the hugojoomla repo. As you’re actively working on it now.

**Comment by joshuabeny1999** [comment]
@davetcc @matt6697  Did it. There is one entry in my DB where that is the case. :
```
mysql> select id, title, modified from zu1fc_content where modified is null;
+-----+-------------------------+---------------------+
| id  | title                   | modified            |
+-----+-------------------------+---------------------+
| 136 | Erlebnispark Tripsdrill | 0000-00-00 00:00:00 |
+-----+-------------------------+---------------------+
```

Strangly in the gui the entry with this title has id 137, which is also in the db and if i try access the 136 it is not allowed. But found that entry in the trash. Had two entries with same title, one deleted in trash. Emptied the joomla trash and ran the script again. Now i have the markdown files. And it shows only info log entries. So it seems to have exported everything.

But i have an issue with UTF8-Symbols in the editor. But found out that the issue is related to the format. If i open the Markdown with Encoding Windows 1252 everything showed correclty.

But that seems not to be compatible with Hugo, due hugo needs utf8:
```
hugo server -D
Start building sites …
hugo v0.87.0-B0C541E4+extended windows/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
Error: Error building site: "C:\Users\joshu\OneDrive\Dokumente\GIT\achterbahnwissen\content\articles\datenschutzerklaerung.md:2:1": failed to unmarshal YAML: yaml: invalid trailing UTF-8 octet
Built in 59 ms
```

I attached the exported file: [datenschutzerklaerung.md](https://github.com/davetcc/hugojoomla/files/7098568/datenschutzerklaerung.md)
This is the page in the frontend:
https://achterbahnwissen.ch/datenschutz.html

I guess the encoding is some issue with the exporter tool. It should export everything to UTF8 and not windows1252. The DB itself is UTF8 encoded:
```
mysql> SELECT default_character_set_name FROM information_schema.SCHEMATA  WHERE schema_name = "achterbahnwissen";
+----------------------------+
| DEFAULT_CHARACTER_SET_NAME |
+----------------------------+
| utf8mb4                    |
+----------------------------+
1 row in set (0.00 sec)
```

Hope I could help with my detailed Test explanation and issue description.

**Comment by matt6697** [comment]
Are you compiling and running the hugojoomla converter on Windows or Linux ?

When opening the generated MD files on WSL2 Linux with VScode, UTF-8 encoding, LF line breaks is detected
![image](https://user-images.githubusercontent.com/32440697/131885162-67ad520a-a3b9-4d2a-b01e-6879a46cb925.png)


When compiling with maven, I notice the following warning which might be related with your encoding issue : **[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!**

```
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.thecoderscorner.web.:hugo-joomla:jar:0.2-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 96, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ----------------< com.thecoderscorner.web.:hugo-joomla >----------------
[INFO] Building Hugo-Joomla 0.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hugo-joomla ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 7 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ hugo-joomla ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 6 source files to /home/matthieu/hugojoomla/target/classes
[INFO] /home/matthieu/hugojoomla/src/main/java/com/thecoderscorner/web/hugojoomla/JoomlaImage.java: /home/matthieu/hugojoomla/src/main/java/com/thecoderscorner/web/hugojoomla/JoomlaImage.java uses unchecked or unsafe operations.
[INFO] /home/matthieu/hugojoomla/src/main/java/com/thecoderscorner/web/hugojoomla/JoomlaImage.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hugo-joomla ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ hugo-joomla ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ hugo-joomla ---
[INFO]
[INFO] --- maven-dependency-plugin:2.8:copy-dependencies (copy-dependencies) @ hugo-joomla ---
[INFO] Copying jsoup-1.13.1.jar to /home/matthieu/hugojoomla/target/lib/jsoup-1.13.1.jar
[INFO] Copying spring-beans-4.3.3.RELEASE.jar to /home/matthieu/hugojoomla/target/lib/spring-beans-4.3.3.RELEASE.jar
[INFO] Copying slf4j-api-1.7.21.jar to /home/matthieu/hugojoomla/target/lib/slf4j-api-1.7.21.jar
[INFO] Copying slf4j-log4j12-1.7.21.jar to /home/matthieu/hugojoomla/target/lib/slf4j-log4j12-1.7.21.jar
[INFO] Copying log4j-1.2.17.jar to /home/matthieu/hugojoomla/target/lib/log4j-1.2.17.jar
[INFO] Copying protobuf-java-3.11.4.jar to /home/matthieu/hugojoomla/target/lib/protobuf-java-3.11.4.jar
[INFO] Copying freemarker-2.3.23.jar to /home/matthieu/hugojoomla/target/lib/freemarker-2.3.23.jar
[INFO] Copying guava-19.0.jar to /home/matthieu/hugojoomla/target/lib/guava-19.0.jar
[INFO] Copying copy_down-1.0.jar to /home/matthieu/hugojoomla/target/lib/copy_down-1.0.jar
[INFO] Copying commons-logging-1.2.jar to /home/matthieu/hugojoomla/target/lib/commons-logging-1.2.jar
[INFO] Copying spring-aop-4.3.3.RELEASE.jar to /home/matthieu/hugojoomla/target/lib/spring-aop-4.3.3.RELEASE.jar
[INFO] Copying spring-tx-4.3.3.RELEASE.jar to /home/matthieu/hugojoomla/target/lib/spring-tx-4.3.3.RELEASE.jar
[INFO] Copying mysql-connector-java-8.0.26.jar to /home/matthieu/hugojoomla/target/lib/mysql-connector-java-8.0.26.jar
[INFO] Copying commons-cli-1.3.1.jar to /home/matthieu/hugojoomla/target/lib/commons-cli-1.3.1.jar
[INFO] Copying junit-4.10.jar to /home/matthieu/hugojoomla/target/lib/junit-4.10.jar
[INFO] Copying spring-context-4.3.3.RELEASE.jar to /home/matthieu/hugojoomla/target/lib/spring-context-4.3.3.RELEASE.jar
[INFO] Copying spring-core-4.3.3.RELEASE.jar to /home/matthieu/hugojoomla/target/lib/spring-core-4.3.3.RELEASE.jar
[INFO] Copying spring-jdbc-4.3.3.RELEASE.jar to /home/matthieu/hugojoomla/target/lib/spring-jdbc-4.3.3.RELEASE.jar
[INFO] Copying spring-expression-4.3.3.RELEASE.jar to /home/matthieu/hugojoomla/target/lib/spring-expression-4.3.3.RELEASE.jar
[INFO] Copying json-simple-1.1.1.jar to /home/matthieu/hugojoomla/target/lib/json-simple-1.1.1.jar
[INFO] Copying hamcrest-core-1.1.jar to /home/matthieu/hugojoomla/target/lib/hamcrest-core-1.1.jar
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ hugo-joomla ---
[INFO] Building jar: /home/matthieu/hugojoomla/target/hugo-joomla-0.2-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ hugo-joomla ---
[INFO] Installing /home/matthieu/hugojoomla/target/hugo-joomla-0.2-SNAPSHOT.jar to /home/matthieu/.m2/repository/com/thecoderscorner/web/hugo-joomla/0.2-SNAPSHOT/hugo-joomla-0.2-SNAPSHOT.jar
[INFO] Installing /home/matthieu/hugojoomla/pom.xml to /home/matthieu/.m2/repository/com/thecoderscorner/web/hugo-joomla/0.2-SNAPSHOT/hugo-joomla-0.2-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.530 s
[INFO] Finished at: 2021-09-02T18:37:18+02:00
[INFO] ------------------------------------------------------------------------
```

Could you please provide the log output of `mvn clean && mvn install` ?

**Comment by joshuabeny1999** [comment]
I compiling on Windows. There is the output:
```
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.thecoderscorner.web.:hugo-joomla:jar:0.2-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 96, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ----------------< com.thecoderscorner.web.:hugo-joomla >----------------
[INFO] Building Hugo-Joomla 0.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hugo-joomla ---
[INFO] Deleting C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.360 s
[INFO] Finished at: 2021-09-02T19:41:00+02:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.thecoderscorner.web.:hugo-joomla:jar:0.2-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 96, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ----------------< com.thecoderscorner.web.:hugo-joomla >----------------
[INFO] Building Hugo-Joomla 0.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hugo-joomla ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 6 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ hugo-joomla ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 6 source files to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\classes
[INFO] /C:/Users/joshu/OneDrive/Dokumente/GIT/hugojoomla/src/main/java/com/thecoderscorner/web/hugojoomla/JoomlaImage.java: C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\src\main\java\com\thecoderscorner\web\hugojoomla\JoomlaImage.java uses unchecked or unsafe operations.
[INFO] /C:/Users/joshu/OneDrive/Dokumente/GIT/hugojoomla/src/main/java/com/thecoderscorner/web/hugojoomla/JoomlaImage.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hugo-joomla ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ hugo-joomla ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ hugo-joomla ---
[INFO]
[INFO] --- maven-dependency-plugin:2.8:copy-dependencies (copy-dependencies) @ hugo-joomla ---
[INFO] Copying jsoup-1.13.1.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\jsoup-1.13.1.jar
[INFO] Copying spring-beans-4.3.3.RELEASE.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\spring-beans-4.3.3.RELEASE.jar
[INFO] Copying slf4j-api-1.7.21.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\slf4j-api-1.7.21.jar
[INFO] Copying slf4j-log4j12-1.7.21.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\slf4j-log4j12-1.7.21.jar
[INFO] Copying log4j-1.2.17.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\log4j-1.2.17.jar
[INFO] Copying protobuf-java-3.11.4.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\protobuf-java-3.11.4.jar
[INFO] Copying freemarker-2.3.23.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\freemarker-2.3.23.jar
[INFO] Copying guava-19.0.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\guava-19.0.jar
[INFO] Copying copy_down-1.0.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\copy_down-1.0.jar
[INFO] Copying commons-logging-1.2.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\commons-logging-1.2.jar
[INFO] Copying spring-aop-4.3.3.RELEASE.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\spring-aop-4.3.3.RELEASE.jar
[INFO] Copying spring-tx-4.3.3.RELEASE.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\spring-tx-4.3.3.RELEASE.jar
[INFO] Copying mysql-connector-java-8.0.26.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\mysql-connector-java-8.0.26.jar
[INFO] Copying commons-cli-1.3.1.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\commons-cli-1.3.1.jar
[INFO] Copying junit-4.10.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\junit-4.10.jar
[INFO] Copying spring-context-4.3.3.RELEASE.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\spring-context-4.3.3.RELEASE.jar
[INFO] Copying spring-core-4.3.3.RELEASE.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\spring-core-4.3.3.RELEASE.jar
[INFO] Copying spring-jdbc-4.3.3.RELEASE.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\spring-jdbc-4.3.3.RELEASE.jar
[INFO] Copying spring-expression-4.3.3.RELEASE.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\spring-expression-4.3.3.RELEASE.jar
[INFO] Copying json-simple-1.1.1.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\json-simple-1.1.1.jar
[INFO] Copying hamcrest-core-1.1.jar to C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\lib\hamcrest-core-1.1.jar
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ hugo-joomla ---
[INFO] Building jar: C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\hugo-joomla-0.2-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ hugo-joomla ---
[INFO] Installing C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\target\hugo-joomla-0.2-SNAPSHOT.jar to C:\Users\joshu\.m2\repository\com\thecoderscorner\web\hugo-joomla\0.2-SNAPSHOT\hugo-joomla-0.2-SNAPSHOT.jar
[INFO] Installing C:\Users\joshu\OneDrive\Dokumente\GIT\hugojoomla\pom.xml to C:\Users\joshu\.m2\repository\com\thecoderscorner\web\hugo-joomla\0.2-SNAPSHOT\hugo-joomla-0.2-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.219 s
[INFO] Finished at: 2021-09-02T19:41:06+02:00
[INFO] ------------------------------------------------------------------------
```

It seems it does not using utf8. In my warning it says Cp1252

**Comment by matt6697** [comment]
Here is your issue : **using platform encoding Cp1252**. Java uses the default system encoding for build and file output as code and file encoding have not explicitly been defined. On a windows platform, Windows 1252 is used.

Could you please try with the code of the `fix/utf8_encoding`  branch of my fork (https://github.com/joomlaext/hugojoomla/tree/fix/utf8_encoding) which should correct the encoding issue on windows to validate the PR #21 ?

**Comment by joshuabeny1999** [comment]
Hi @matt6697 

The issue is fixed and everything is now in UTF8. 

But what i dedected. The new converter removes a lot of html. Images would be converted to markdown, but iframes will got removed completly. I have some pages with embed youtube videos. They are now completly gone. Here the makdown of this page: https://achterbahnwissen.ch/videos/holidaypark-videos.html
```md
---
title: "Holiday Park Videos"
description: ""
tags: [  ]
type: "post"
date: "2015-04-10"
author:  "admin"
menu: "videos"
---
Hier bist du bei den Videos des Holiday Parks. Ich wünsche dir viel Spass beim betrachten der Videos. Hast du den Bericht des Holiday Parks schon gelesen? Wenn Nein, dann soltest du dies tun. [Hier](index.php?option=com_content&view=article&id=71&Itemid=305 "Holiday Park") kommst du direkt zum Bericht.

**Freizeitparkfilm**

**Onride-Videos:**

**Sky Scream:**

**Expedition GeForce:**
```

Kind regards,
Joshua

**Comment by matt6697** [comment]
Thanks for the feedback. This is why we choosed to make markdown conversion optional => check the new **htmltomarkdown ** parameter to disable markdown conversion if it is not suitable for your website.

**Comment by joshuabeny1999** [comment]
Okay. Yeah it is suitable for 90% of the website. If I want the links again, I could find them easily, due they are own uploaded videos. 

Currently I need to find first a suitable theme and then it is still a lot of work. But the converter helps to have the text at least as markdown. Also posts is not suitable for my website due they are more static pages. But will first getting used to hugo again. The last website I did was just a blog and that is a few years back.
